import {
  Student,
  Subject,
  AttendanceRecord,
  TimetableSlot,
  MarkRecord,
  Assignment,
  Exam,
  CampusNotification,
} from '../types';
import { AKTU_BTECH_3RD_YEAR_SYLLABUS } from '../data/aktuSyllabus';

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'student-vikas',
    rollNumber: '2200270100002',
    name: 'Vikas Gupta',
    email: 'vikasgupta22986@gmail.com',
    phone: '+91 98765 22986',
    department: 'Computer Science & Engineering',
    semester: 6,
    section: 'CSE-A',
    cgpa: 8.84,
    sgpa: 9.10,
    batch: '2022-2026',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&auto=format&fit=crop&q=80',
    faceRegistered: true,
    faceConsentGiven: true,
    faceRegisteredAt: '2026-02-10T10:30:00Z',
    address: 'Vikas Nagar, Sector 4, Lucknow, Uttar Pradesh',
    guardianName: 'Ramesh Gupta',
    guardianPhone: '+91 98765 11001',
    faceEmbedding: Array.from({ length: 128 }, (_, i) => Math.sin(i * 0.42) * 0.5 + 0.5),
  },
  {
    id: 'student-ankit-k',
    rollNumber: '2200270100001',
    name: 'Ankit Kannaujiya',
    email: 'ankit.kannaujiya@aktu.ac.in',
    phone: '+91 98765 10001',
    department: 'Computer Science & Engineering',
    semester: 6,
    section: 'CSE-A',
    cgpa: 8.62,
    sgpa: 8.80,
    batch: '2022-2026',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    faceRegistered: true,
    faceConsentGiven: true,
    faceRegisteredAt: '2026-02-10T11:00:00Z',
    address: 'Indira Nagar, Block C, Lucknow, UP',
    guardianName: 'Sunil Kannaujiya',
    guardianPhone: '+91 98765 11002',
    faceEmbedding: Array.from({ length: 128 }, (_, i) => Math.cos(i * 0.35) * 0.5 + 0.5),
  },
  {
    id: 'student-krishna',
    rollNumber: '2200270100003',
    name: 'Krishna Yadav',
    email: 'krishna.yadav@aktu.ac.in',
    phone: '+91 98765 10003',
    department: 'Computer Science & Engineering',
    semester: 6,
    section: 'CSE-A',
    cgpa: 8.95,
    sgpa: 9.25,
    batch: '2022-2026',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    faceRegistered: true,
    faceConsentGiven: true,
    faceRegisteredAt: '2026-02-11T09:15:00Z',
    address: 'Gomti Nagar Extension, Lucknow, UP',
    guardianName: 'Devendra Yadav',
    guardianPhone: '+91 98765 11003',
    faceEmbedding: Array.from({ length: 128 }, (_, i) => Math.sin(i * 0.51) * 0.5 + 0.5),
  },
  {
    id: 'student-aryan',
    rollNumber: '2200270100004',
    name: 'Aryan Jaiswal',
    email: 'aryan.jaiswal@aktu.ac.in',
    phone: '+91 98765 10004',
    department: 'Computer Science & Engineering',
    semester: 6,
    section: 'CSE-A',
    cgpa: 7.88,
    sgpa: 8.10,
    batch: '2022-2026',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    faceRegistered: true,
    faceConsentGiven: true,
    faceRegisteredAt: '2026-02-11T14:30:00Z',
    address: 'Aliganj, Sector J, Lucknow, UP',
    guardianName: 'Manoj Jaiswal',
    guardianPhone: '+91 98765 11004',
    faceEmbedding: Array.from({ length: 128 }, (_, i) => Math.cos(i * 0.48) * 0.5 + 0.5),
  },
  {
    id: 'student-ankit-y',
    rollNumber: '2200270100005',
    name: 'Ankit Yadav',
    email: 'ankit.yadav@aktu.ac.in',
    phone: '+91 98765 10005',
    department: 'Computer Science & Engineering',
    semester: 6,
    section: 'CSE-A',
    cgpa: 8.35,
    sgpa: 8.50,
    batch: '2022-2026',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80',
    faceRegistered: true,
    faceConsentGiven: true,
    faceRegisteredAt: '2026-02-12T10:00:00Z',
    address: 'Hazratganj, Lucknow, UP',
    guardianName: 'Vinod Yadav',
    guardianPhone: '+91 98765 11005',
    faceEmbedding: Array.from({ length: 128 }, (_, i) => Math.sin(i * 0.65) * 0.5 + 0.5),
  },
  {
    id: 'student-ragini',
    rollNumber: '2200270100006',
    name: 'Ragini Gangwar',
    email: 'ragini.gangwar@aktu.ac.in',
    phone: '+91 98765 10006',
    department: 'Computer Science & Engineering',
    semester: 6,
    section: 'CSE-A',
    cgpa: 9.42,
    sgpa: 9.60,
    batch: '2022-2026',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
    faceRegistered: true,
    faceConsentGiven: true,
    faceRegisteredAt: '2026-02-12T11:45:00Z',
    address: 'Civil Lines, Bareilly, UP',
    guardianName: 'Dr. S.P. Gangwar',
    guardianPhone: '+91 98765 11006',
    faceEmbedding: Array.from({ length: 128 }, (_, i) => Math.cos(i * 0.62) * 0.5 + 0.5),
  },
  {
    id: 'student-avinash',
    rollNumber: '2200270100007',
    name: 'Avinash Kushwaha',
    email: 'avinash.kushwaha@aktu.ac.in',
    phone: '+91 98765 10007',
    department: 'Computer Science & Engineering',
    semester: 6,
    section: 'CSE-A',
    cgpa: 8.18,
    sgpa: 8.30,
    batch: '2022-2026',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&auto=format&fit=crop&q=80',
    faceRegistered: true,
    faceConsentGiven: true,
    faceRegisteredAt: '2026-02-13T12:30:00Z',
    address: 'Rajaji Puram, Sector 12, Lucknow, UP',
    guardianName: 'R.K. Kushwaha',
    guardianPhone: '+91 98765 11007',
    faceEmbedding: Array.from({ length: 128 }, (_, i) => Math.sin(i * 0.73) * 0.5 + 0.5),
  },
  {
    id: 'student-pallavi',
    rollNumber: '2200270100008',
    name: 'Pallavi Pandey',
    email: 'pallavi.pandey@aktu.ac.in',
    phone: '+91 98765 10008',
    department: 'Computer Science & Engineering',
    semester: 6,
    section: 'CSE-B',
    cgpa: 9.15,
    sgpa: 9.30,
    batch: '2022-2026',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    faceRegistered: true,
    faceConsentGiven: true,
    faceRegisteredAt: '2026-02-13T14:10:00Z',
    address: 'Mahanagar, Lucknow, UP',
    guardianName: 'Harish Pandey',
    guardianPhone: '+91 98765 11008',
    faceEmbedding: Array.from({ length: 128 }, (_, i) => Math.cos(i * 0.77) * 0.5 + 0.5),
  },
  {
    id: 'student-parul',
    rollNumber: '2200270100009',
    name: 'Parul Pandey',
    email: 'parul.pandey@aktu.ac.in',
    phone: '+91 98765 10009',
    department: 'Computer Science & Engineering',
    semester: 6,
    section: 'CSE-B',
    cgpa: 8.92,
    sgpa: 9.05,
    batch: '2022-2026',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80',
    faceRegistered: true,
    faceConsentGiven: true,
    faceRegisteredAt: '2026-02-14T09:40:00Z',
    address: 'Janki Puram, Sector F, Lucknow, UP',
    guardianName: 'Harish Pandey',
    guardianPhone: '+91 98765 11008',
    faceEmbedding: Array.from({ length: 128 }, (_, i) => Math.sin(i * 0.81) * 0.5 + 0.5),
  },
  {
    id: 'student-sanjana',
    rollNumber: '2200270100010',
    name: 'Sanjana Yadav',
    email: 'sanjana.yadav@aktu.ac.in',
    phone: '+91 98765 10010',
    department: 'Computer Science & Engineering',
    semester: 6,
    section: 'CSE-B',
    cgpa: 8.76,
    sgpa: 8.90,
    batch: '2022-2026',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
    faceRegistered: true,
    faceConsentGiven: true,
    faceRegisteredAt: '2026-02-14T11:20:00Z',
    address: 'Ashiyana Colony, Kanpur Road, Lucknow, UP',
    guardianName: 'Mahendra Yadav',
    guardianPhone: '+91 98765 11010',
    faceEmbedding: Array.from({ length: 128 }, (_, i) => Math.cos(i * 0.84) * 0.5 + 0.5),
  },
  {
    id: 'student-anamika',
    rollNumber: '2200270100011',
    name: 'Anamika',
    email: 'anamika@aktu.ac.in',
    phone: '+91 98765 10011',
    department: 'Computer Science & Engineering',
    semester: 6,
    section: 'CSE-B',
    cgpa: 8.54,
    sgpa: 8.65,
    batch: '2022-2026',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&auto=format&fit=crop&q=80',
    faceRegistered: true,
    faceConsentGiven: true,
    faceRegisteredAt: '2026-02-15T10:15:00Z',
    address: 'Faizabad Road, Matiyari, Lucknow, UP',
    guardianName: 'Ajay Verma',
    guardianPhone: '+91 98765 11011',
    faceEmbedding: Array.from({ length: 128 }, (_, i) => Math.sin(i * 0.89) * 0.5 + 0.5),
  },
  {
    id: 'student-yasir',
    rollNumber: '2200270100012',
    name: 'Yasir Ali',
    email: 'yasir.ali@aktu.ac.in',
    phone: '+91 98765 10012',
    department: 'Computer Science & Engineering',
    semester: 6,
    section: 'CSE-B',
    cgpa: 8.40,
    sgpa: 8.55,
    batch: '2022-2026',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80',
    faceRegistered: true,
    faceConsentGiven: true,
    faceRegisteredAt: '2026-02-15T13:00:00Z',
    address: 'Old City, Chowk, Lucknow, UP',
    guardianName: 'Akhtar Ali',
    guardianPhone: '+91 98765 11012',
    faceEmbedding: Array.from({ length: 128 }, (_, i) => Math.cos(i * 0.92) * 0.5 + 0.5),
  },
  {
    id: 'student-sachin',
    rollNumber: '2200270100013',
    name: 'Sachin Chauhan',
    email: 'sachin.chauhan@aktu.ac.in',
    phone: '+91 98765 10013',
    department: 'Computer Science & Engineering',
    semester: 6,
    section: 'CSE-B',
    cgpa: 7.95,
    sgpa: 8.15,
    batch: '2022-2026',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=200&auto=format&fit=crop&q=80',
    faceRegistered: false,
    faceConsentGiven: false,
    address: 'Dubagga, Hardoi Road, Lucknow, UP',
    guardianName: 'Surendra Chauhan',
    guardianPhone: '+91 98765 11013',
  },
  {
    id: 'student-vipin',
    rollNumber: '2200270100014',
    name: 'Vipin Yadav',
    email: 'vipin.yadav@aktu.ac.in',
    phone: '+91 98765 10014',
    department: 'Computer Science & Engineering',
    semester: 6,
    section: 'CSE-B',
    cgpa: 8.28,
    sgpa: 8.40,
    batch: '2022-2026',
    avatarUrl: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=200&auto=format&fit=crop&q=80',
    faceRegistered: true,
    faceConsentGiven: true,
    faceRegisteredAt: '2026-02-16T15:30:00Z',
    address: 'Vrindavan Colony, Telibagh, Lucknow, UP',
    guardianName: 'Ramsurat Yadav',
    guardianPhone: '+91 98765 11014',
    faceEmbedding: Array.from({ length: 128 }, (_, i) => Math.sin(i * 0.95) * 0.5 + 0.5),
  },
  {
    id: 'student-raj',
    rollNumber: '2200270100015',
    name: 'Raj',
    email: 'raj.cse@aktu.ac.in',
    phone: '+91 98765 10015',
    department: 'Computer Science & Engineering',
    semester: 6,
    section: 'CSE-B',
    cgpa: 8.05,
    sgpa: 8.20,
    batch: '2022-2026',
    avatarUrl: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=200&auto=format&fit=crop&q=80',
    faceRegistered: true,
    faceConsentGiven: true,
    faceRegisteredAt: '2026-02-17T11:00:00Z',
    address: 'Charbagh Station Road, Lucknow, UP',
    guardianName: 'Satya Prakash',
    guardianPhone: '+91 98765 11015',
    faceEmbedding: Array.from({ length: 128 }, (_, i) => Math.cos(i * 0.97) * 0.5 + 0.5),
  },
  {
    id: 'student-mazharul',
    rollNumber: '2200270100016',
    name: 'Mazharul',
    email: 'mazharul@aktu.ac.in',
    phone: '+91 98765 10016',
    department: 'Computer Science & Engineering',
    semester: 6,
    section: 'CSE-B',
    cgpa: 8.68,
    sgpa: 8.85,
    batch: '2022-2026',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    faceRegistered: true,
    faceConsentGiven: true,
    faceRegisteredAt: '2026-02-17T14:40:00Z',
    address: 'Vikas Nagar, Sector 8, Lucknow, UP',
    guardianName: 'Tariq Hassan',
    guardianPhone: '+91 98765 11016',
    faceEmbedding: Array.from({ length: 128 }, (_, i) => Math.sin(i * 0.99) * 0.5 + 0.5),
  },
];

// Official AKTU B.Tech 3rd Year (Semester 5 & 6) Subjects
export const INITIAL_SUBJECTS: Subject[] = [
  {
    id: 'sub-kcs501',
    code: 'KCS-501',
    name: 'Database Management Systems',
    department: 'Computer Science & Engineering',
    semester: 5,
    credits: 4,
    facultyName: 'Dr. Arvind Sharma',
    facultyEmail: 'arvind.sharma@aktu.ac.in',
    roomNumber: 'Lecture Hall 301',
    totalClasses: 42,
    syllabusTopics: [
      'Unit 1: ER Model, Three Schema Architecture, Relational Mapping',
      'Unit 2: Relational Algebra, Tuple Calculus, Advanced SQL & Triggers',
      'Unit 3: Functional Dependencies, Decomposition, Normal Forms (1NF, 2NF, 3NF, BCNF, 4NF)',
      'Unit 4: Transaction Processing, ACID Properties, Serializability, Concurrency Protocols (2PL)',
      'Unit 5: Indexing, B-Trees, B+ Trees, Hashing, Log-Based Database Recovery (ARIES)',
    ],
    syllabusUnits: AKTU_BTECH_3RD_YEAR_SYLLABUS['KCS-501']?.units,
    textbooks: AKTU_BTECH_3RD_YEAR_SYLLABUS['KCS-501']?.textbooks,
    referenceBooks: AKTU_BTECH_3RD_YEAR_SYLLABUS['KCS-501']?.referenceBooks,
  },
  {
    id: 'sub-kcs502',
    code: 'KCS-502',
    name: 'Compiler Design',
    department: 'Computer Science & Engineering',
    semester: 5,
    credits: 4,
    facultyName: 'Prof. R.K. Dixit',
    facultyEmail: 'rk.dixit@aktu.ac.in',
    roomNumber: 'Lecture Hall 302',
    totalClasses: 40,
    syllabusTopics: [
      'Unit 1: Structure of Compiler, Lexical Analysis, Regular Expressions to DFA, Lex Tool',
      'Unit 2: Syntax Analysis, Context-Free Grammars, LL(1), LR(0), SLR(1), LALR(1) Parsing Tables',
      'Unit 3: Syntax Directed Translation (SDD/SDTS), Intermediate Code Generation, Three-Address Code',
      'Unit 4: Symbol Table Management, Runtime Storage Administration, Activation Records',
      'Unit 5: Code Optimization, Basic Blocks & Flow Graphs, Loop Invariants, Peephole Optimization',
    ],
    syllabusUnits: AKTU_BTECH_3RD_YEAR_SYLLABUS['KCS-502']?.units,
    textbooks: AKTU_BTECH_3RD_YEAR_SYLLABUS['KCS-502']?.textbooks,
    referenceBooks: AKTU_BTECH_3RD_YEAR_SYLLABUS['KCS-502']?.referenceBooks,
  },
  {
    id: 'sub-kcs503',
    code: 'KCS-503',
    name: 'Design and Analysis of Algorithms',
    department: 'Computer Science & Engineering',
    semester: 5,
    credits: 4,
    facultyName: 'Dr. Sunita Verma',
    facultyEmail: 'sunita.verma@aktu.ac.in',
    roomNumber: 'Lecture Hall 303',
    totalClasses: 44,
    syllabusTopics: [
      'Unit 1: Asymptotic Notations, Recurrences (Master Theorem), Divide and Conquer (Merge, Quick Sort)',
      'Unit 2: Red-Black Trees, Binomial & Fibonacci Heaps, Disjoint Set Union (Union-Find)',
      'Unit 3: Greedy Strategy (Huffman, Knapsack) & Dynamic Programming (0/1 Knapsack, LCS, Floyd-Warshall)',
      'Unit 4: Graph Traversals (BFS, DFS), Minimum Spanning Trees (Kruskal, Prim), String Matching (KMP)',
      'Unit 5: P, NP, NP-Complete Reductions (Cook’s Theorem, 3-SAT, Vertex Cover, TSP) & Approximation',
    ],
    syllabusUnits: AKTU_BTECH_3RD_YEAR_SYLLABUS['KCS-503']?.units,
    textbooks: AKTU_BTECH_3RD_YEAR_SYLLABUS['KCS-503']?.textbooks,
    referenceBooks: AKTU_BTECH_3RD_YEAR_SYLLABUS['KCS-503']?.referenceBooks,
  },
  {
    id: 'sub-kcs054',
    code: 'KCS-054',
    name: 'Machine Learning Techniques',
    department: 'Computer Science & Engineering',
    semester: 5,
    credits: 3,
    facultyName: 'Dr. Ashish Srivastava',
    facultyEmail: 'ashish.srivastava@aktu.ac.in',
    roomNumber: 'Seminar Hall 401',
    totalClasses: 36,
    syllabusTopics: [
      'Unit 1: Supervised Learning, Linear Regression, Regularization (Lasso, Ridge), Gradient Descent',
      'Unit 2: Logistic Regression, Multi-class Classification, Support Vector Machines & Kernel Trick',
      'Unit 3: Decision Trees (ID3, CART), Ensemble Methods (Random Forests, AdaBoost, XGBoost)',
      'Unit 4: Unsupervised Clustering (K-Means, Hierarchical), PCA Dimensionality Reduction',
      'Unit 5: Artificial Neural Networks, Backpropagation, Introduction to CNNs and Deep Learning',
    ],
    syllabusUnits: AKTU_BTECH_3RD_YEAR_SYLLABUS['KCS-054']?.units,
    textbooks: AKTU_BTECH_3RD_YEAR_SYLLABUS['KCS-054']?.textbooks,
    referenceBooks: AKTU_BTECH_3RD_YEAR_SYLLABUS['KCS-054']?.referenceBooks,
  },
  {
    id: 'sub-knc501',
    code: 'KNC-501',
    name: 'Constitution of India, Law and Engineering',
    department: 'Humanities & Social Sciences',
    semester: 5,
    credits: 2,
    facultyName: 'Dr. Meena Tripathi',
    facultyEmail: 'meena.tripathi@aktu.ac.in',
    roomNumber: 'Lecture Hall 204',
    totalClasses: 28,
    syllabusTopics: [
      'Unit 1: Constituent Assembly, Preamble, Salient Features of Indian Constitution',
      'Unit 2: Fundamental Rights (Articles 12-35), Directive Principles (DPSP), Fundamental Duties',
      'Unit 3: Union Executive, Parliament, Judiciary (Supreme Court, Judicial Review, PIL)',
      'Unit 4: Indian Contract Act 1872, Law of Torts, Product Liability, Dispute Resolution',
      'Unit 5: Intellectual Property Rights (IPR, Patents, Copyrights) & Information Technology Act 2000',
    ],
    syllabusUnits: AKTU_BTECH_3RD_YEAR_SYLLABUS['KNC-501']?.units,
    textbooks: AKTU_BTECH_3RD_YEAR_SYLLABUS['KNC-501']?.textbooks,
    referenceBooks: AKTU_BTECH_3RD_YEAR_SYLLABUS['KNC-501']?.referenceBooks,
  },
  {
    id: 'sub-kcs601',
    code: 'KCS-601',
    name: 'Software Engineering',
    department: 'Computer Science & Engineering',
    semester: 6,
    credits: 3,
    facultyName: 'Prof. Manoj Kumar',
    facultyEmail: 'manoj.kumar@aktu.ac.in',
    roomNumber: 'Lecture Hall 304',
    totalClasses: 36,
    syllabusTopics: [
      'Unit 1: Software Process Models, Agile Scrum Methodology, IEEE-830 SRS Document',
      'Unit 2: Architectural Design, Modularity, Cohesion, Coupling, UML Object-Oriented Modeling',
      'Unit 3: Software Metrics, Function Point Analysis, COCOMO II, PERT/CPM Scheduling, Risk Management',
      'Unit 4: White-Box Testing (Basis Path, Cyclomatic Complexity), Black-Box Testing (BVA, Equivalence)',
      'Unit 5: Maintenance Types, CI/CD DevOps Pipelines, CMMI Level 1-5, ISO 9000 & Six Sigma',
    ],
    syllabusUnits: AKTU_BTECH_3RD_YEAR_SYLLABUS['KCS-601']?.units,
    textbooks: AKTU_BTECH_3RD_YEAR_SYLLABUS['KCS-601']?.textbooks,
    referenceBooks: AKTU_BTECH_3RD_YEAR_SYLLABUS['KCS-601']?.referenceBooks,
  },
  {
    id: 'sub-kcs602',
    code: 'KCS-602',
    name: 'Web Technology',
    department: 'Computer Science & Engineering',
    semester: 6,
    credits: 4,
    facultyName: 'Er. Amit Shukla',
    facultyEmail: 'amit.shukla@aktu.ac.in',
    roomNumber: 'Lecture Hall 305',
    totalClasses: 42,
    syllabusTopics: [
      'Unit 1: HTTP/2 Architecture, Semantic HTML5, CSS3 Flexbox, CSS Grid & Responsive Design',
      'Unit 2: Modern ES6+ JavaScript, Event Loop, Promises, Async/Await, DOM State Manipulation',
      'Unit 3: Node.js V8 Non-Blocking I/O, Express.js RESTful API Architecture, Middleware Pipelines',
      'Unit 4: MongoDB Mongoose ODM, MySQL Connection Pooling, Redis Caching, Session Management',
      'Unit 5: OWASP Security (XSS, CSRF, SQLi), JWT Auth, React.js Single Page Applications & Cloud Run',
    ],
    syllabusUnits: AKTU_BTECH_3RD_YEAR_SYLLABUS['KCS-602']?.units,
    textbooks: AKTU_BTECH_3RD_YEAR_SYLLABUS['KCS-602']?.textbooks,
    referenceBooks: AKTU_BTECH_3RD_YEAR_SYLLABUS['KCS-602']?.referenceBooks,
  },
  {
    id: 'sub-kcs603',
    code: 'KCS-603',
    name: 'Computer Networks',
    department: 'Computer Science & Engineering',
    semester: 6,
    credits: 4,
    facultyName: 'Dr. Neha Saxena',
    facultyEmail: 'neha.saxena@aktu.ac.in',
    roomNumber: 'Lecture Hall 306',
    totalClasses: 42,
    syllabusTopics: [
      'Unit 1: OSI 7-Layer Model, TCP/IP Suite, Transmission Media, Packet Switching, Multiplexing',
      'Unit 2: Data Link Framing, CRC Error Detection, Sliding Window Protocols (GBN, SR), CSMA/CD, Wi-Fi',
      'Unit 3: IPv4/IPv6 Addressing, VLSM Subnetting, NAT, Routing Protocols (OSPF Link State, BGP)',
      'Unit 4: Transport Sockets, TCP 3-Way Handshake, TCP Congestion Control (AIMD, Tahoe, Reno), UDP',
      'Unit 5: Application Layer (DNS, HTTP/3, SMTP), TLS/SSL Handshake, RSA Cryptography, Firewalls',
    ],
    syllabusUnits: AKTU_BTECH_3RD_YEAR_SYLLABUS['KCS-603']?.units,
    textbooks: AKTU_BTECH_3RD_YEAR_SYLLABUS['KCS-603']?.textbooks,
    referenceBooks: AKTU_BTECH_3RD_YEAR_SYLLABUS['KCS-603']?.referenceBooks,
  },
  {
    id: 'sub-koe068',
    code: 'KOE-068',
    name: 'Cloud Computing',
    department: 'Open Elective (CSE/IT)',
    semester: 6,
    credits: 3,
    facultyName: 'Prof. Alok Mishra',
    facultyEmail: 'alok.mishra@aktu.ac.in',
    roomNumber: 'Lecture Hall 402',
    totalClasses: 36,
    syllabusTopics: [
      'Unit 1: NIST Cloud Definition, Service Models (IaaS, PaaS, SaaS, Serverless), Multi-Cloud Strategy',
      'Unit 2: Virtualization Hypervisors (Type 1 & 2), Hardware VT-x, Docker Containers & Kubernetes',
      'Unit 3: Cloud Storage Systems, Distributed File Systems (GFS, HDFS), Managed Database Services',
      'Unit 4: Shared Responsibility Security Model, Cloud IAM, RBAC, Encryption, SLAs and Compliance',
      'Unit 5: Cloud Providers (GCP, AWS, Azure), FinOps Cloud Economics, Serverless & Edge Computing',
    ],
    syllabusUnits: AKTU_BTECH_3RD_YEAR_SYLLABUS['KOE-068']?.units,
    textbooks: AKTU_BTECH_3RD_YEAR_SYLLABUS['KOE-068']?.textbooks,
    referenceBooks: AKTU_BTECH_3RD_YEAR_SYLLABUS['KOE-068']?.referenceBooks,
  },
  {
    id: 'sub-kcs551',
    code: 'KCS-551',
    name: 'Database Management Systems Lab',
    department: 'Computer Science & Engineering',
    semester: 5,
    credits: 1,
    facultyName: 'Er. R.P. Singh',
    facultyEmail: 'rp.singh@aktu.ac.in',
    roomNumber: 'Database Systems Lab 1',
    totalClasses: 16,
    syllabusTopics: [
      'Experiment 1: Database Schema creation with primary and foreign key constraints in MySQL/PostgreSQL',
      'Experiment 2: Executing nested subqueries, correlated queries, and complex joins',
      'Experiment 3: Creating and managing Views, Triggers, and Stored Procedures with PL/SQL',
      'Experiment 4: Implementation of B+ Tree indexing and query execution plan analysis (EXPLAIN ANALYZE)',
      'Experiment 5: Simulating concurrent transactions, testing ACID properties and serializability locks',
    ],
  },
  {
    id: 'sub-kcs552',
    code: 'KCS-552',
    name: 'Compiler Design Lab',
    department: 'Computer Science & Engineering',
    semester: 5,
    credits: 1,
    facultyName: 'Er. Swati Gupta',
    facultyEmail: 'swati.gupta@aktu.ac.in',
    roomNumber: 'System Software Lab 2',
    totalClasses: 16,
    syllabusTopics: [
      'Experiment 1: Implementation of a Lexical Analyzer for C language using C/C++',
      'Experiment 2: Writing a Lex/Flex program to identify tokens, constants, identifiers, and comments',
      'Experiment 3: Computation of FIRST and FOLLOW sets for a given Context-Free Grammar',
      'Experiment 4: Implementation of predictive LL(1) parsing table and input string validation',
      'Experiment 5: Writing Yacc/Bison specifications for arithmetic expression evaluation and intermediate TAC',
    ],
  },
  {
    id: 'sub-kcs553',
    code: 'KCS-553',
    name: 'Design and Analysis of Algorithms Lab',
    department: 'Computer Science & Engineering',
    semester: 5,
    credits: 1,
    facultyName: 'Er. Deepak Maurya',
    facultyEmail: 'deepak.maurya@aktu.ac.in',
    roomNumber: 'Algorithm Computing Lab 3',
    totalClasses: 16,
    syllabusTopics: [
      'Experiment 1: Sorting runtime comparison: Quick Sort vs Randomized Quick Sort vs Merge Sort',
      'Experiment 2: Implementation of Red-Black Tree insertion and rotation invariants',
      'Experiment 3: Dynamic Programming implementations: 0/1 Knapsack, LCS, and Matrix Chain Multiplication',
      'Experiment 4: Graph shortest path implementations: Dijkstra and Bellman-Ford algorithms',
      'Experiment 5: String Matching algorithms: Knuth-Morris-Pratt (KMP) prefix LPS array and Rabin-Karp',
    ],
  },
  {
    id: 'sub-kcs651',
    code: 'KCS-651',
    name: 'Software Engineering Lab',
    department: 'Computer Science & Engineering',
    semester: 6,
    credits: 1,
    facultyName: 'Er. Pooja Mishra',
    facultyEmail: 'pooja.mishra@aktu.ac.in',
    roomNumber: 'CASE Tools Lab',
    totalClasses: 16,
    syllabusTopics: [
      'Experiment 1: Preparation of Software Requirements Specification (SRS) for Real-World Systems (IEEE-830)',
      'Experiment 2: Creation of Use Case Diagrams, Class Diagrams, and Sequence Diagrams using StarUML',
      'Experiment 3: Estimation of software project effort and duration using COCOMO model',
      'Experiment 4: Automated Unit Testing and calculating McCabe Cyclomatic Complexity using JUnit/Jest',
      'Experiment 5: Designing continuous integration build workflows using GitHub Actions',
    ],
  },
  {
    id: 'sub-kcs652',
    code: 'KCS-652',
    name: 'Web Technology Lab',
    department: 'Computer Science & Engineering',
    semester: 6,
    credits: 1,
    facultyName: 'Er. Amit Shukla',
    facultyEmail: 'amit.shukla@aktu.ac.in',
    roomNumber: 'Web Development Lab 4',
    totalClasses: 16,
    syllabusTopics: [
      'Experiment 1: Building a responsive multi-page web layout using HTML5, CSS3 Grid, and Flexbox',
      'Experiment 2: Client-side dynamic form validation and DOM manipulation using ES6+ JavaScript',
      'Experiment 3: Creating a secure RESTful API with Node.js, Express, and JWT Authentication',
      'Experiment 4: Connecting Express backend to MongoDB/Mongoose with full CRUD operations',
      'Experiment 5: Developing and deploying a single-page React frontend application connected to REST API',
    ],
  },
  {
    id: 'sub-kcs653',
    code: 'KCS-653',
    name: 'Computer Networks Lab',
    department: 'Computer Science & Engineering',
    semester: 6,
    credits: 1,
    facultyName: 'Er. Sandeep Joshi',
    facultyEmail: 'sandeep.joshi@aktu.ac.in',
    roomNumber: 'Network Computing Lab 3',
    totalClasses: 16,
    syllabusTopics: [
      'Experiment 1: Network packet capturing and protocol analysis (HTTP, DNS, TCP) using Wireshark',
      'Experiment 2: Implementation of TCP and UDP Client-Server Socket Communication in C/Python',
      'Experiment 3: VLSM Subnetting calculation and router interface configuration in Cisco Packet Tracer',
      'Experiment 4: Simulating Distance Vector Routing and Link State Routing protocols',
      'Experiment 5: Implementation of CRC Error Detection and Hamming Code error correction algorithms',
    ],
  },
];

// Weekly AKTU CSE 3rd Year Timetable
export const INITIAL_TIMETABLE: TimetableSlot[] = [
  // Monday
  {
    id: 'tt-mon-1',
    day: 'Monday',
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    subjectId: 'sub-kcs501',
    subjectCode: 'KCS-501',
    subjectName: 'Database Management Systems',
    facultyName: 'Dr. Arvind Sharma',
    roomNumber: 'LH-301',
    type: 'Theory',
    semester: 6,
    section: 'CSE-A',
  },
  {
    id: 'tt-mon-2',
    day: 'Monday',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    subjectId: 'sub-kcs502',
    subjectCode: 'KCS-502',
    subjectName: 'Compiler Design',
    facultyName: 'Prof. R.K. Dixit',
    roomNumber: 'LH-302',
    type: 'Theory',
    semester: 6,
    section: 'CSE-A',
  },
  {
    id: 'tt-mon-3',
    day: 'Monday',
    startTime: '11:15 AM',
    endTime: '12:15 PM',
    subjectId: 'sub-kcs503',
    subjectCode: 'KCS-503',
    subjectName: 'Design and Analysis of Algorithms',
    facultyName: 'Dr. Sunita Verma',
    roomNumber: 'LH-303',
    type: 'Theory',
    semester: 6,
    section: 'CSE-A',
  },
  {
    id: 'tt-mon-4',
    day: 'Monday',
    startTime: '01:30 PM',
    endTime: '03:30 PM',
    subjectId: 'sub-kcs551',
    subjectCode: 'KCS-551',
    subjectName: 'DBMS Lab',
    facultyName: 'Er. R.P. Singh',
    roomNumber: 'Lab 1',
    type: 'Lab',
    semester: 6,
    section: 'CSE-A',
  },
  // Tuesday
  {
    id: 'tt-tue-1',
    day: 'Tuesday',
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    subjectId: 'sub-kcs601',
    subjectCode: 'KCS-601',
    subjectName: 'Software Engineering',
    facultyName: 'Prof. Manoj Kumar',
    roomNumber: 'LH-304',
    type: 'Theory',
    semester: 6,
    section: 'CSE-A',
  },
  {
    id: 'tt-tue-2',
    day: 'Tuesday',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    subjectId: 'sub-kcs602',
    subjectCode: 'KCS-602',
    subjectName: 'Web Technology',
    facultyName: 'Er. Amit Shukla',
    roomNumber: 'LH-305',
    type: 'Theory',
    semester: 6,
    section: 'CSE-A',
  },
  {
    id: 'tt-tue-3',
    day: 'Tuesday',
    startTime: '11:15 AM',
    endTime: '12:15 PM',
    subjectId: 'sub-kcs603',
    subjectCode: 'KCS-603',
    subjectName: 'Computer Networks',
    facultyName: 'Dr. Neha Saxena',
    roomNumber: 'LH-306',
    type: 'Theory',
    semester: 6,
    section: 'CSE-A',
  },
  {
    id: 'tt-tue-4',
    day: 'Tuesday',
    startTime: '01:30 PM',
    endTime: '03:30 PM',
    subjectId: 'sub-kcs552',
    subjectCode: 'KCS-552',
    subjectName: 'Compiler Design Lab',
    facultyName: 'Er. Swati Gupta',
    roomNumber: 'Lab 2',
    type: 'Lab',
    semester: 6,
    section: 'CSE-A',
  },
  // Wednesday
  {
    id: 'tt-wed-1',
    day: 'Wednesday',
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    subjectId: 'sub-kcs501',
    subjectCode: 'KCS-501',
    subjectName: 'Database Management Systems',
    facultyName: 'Dr. Arvind Sharma',
    roomNumber: 'LH-301',
    type: 'Theory',
    semester: 6,
    section: 'CSE-A',
  },
  {
    id: 'tt-wed-2',
    day: 'Wednesday',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    subjectId: 'sub-kcs054',
    subjectCode: 'KCS-054',
    subjectName: 'Machine Learning Techniques',
    facultyName: 'Dr. Ashish Srivastava',
    roomNumber: 'SH-401',
    type: 'Theory',
    semester: 6,
    section: 'CSE-A',
  },
  {
    id: 'tt-wed-3',
    day: 'Wednesday',
    startTime: '11:15 AM',
    endTime: '12:15 PM',
    subjectId: 'sub-koe068',
    subjectCode: 'KOE-068',
    subjectName: 'Cloud Computing',
    facultyName: 'Prof. Alok Mishra',
    roomNumber: 'LH-402',
    type: 'Theory',
    semester: 6,
    section: 'CSE-A',
  },
  {
    id: 'tt-wed-4',
    day: 'Wednesday',
    startTime: '01:30 PM',
    endTime: '03:30 PM',
    subjectId: 'sub-kcs553',
    subjectCode: 'KCS-553',
    subjectName: 'DAA Lab',
    facultyName: 'Er. Deepak Maurya',
    roomNumber: 'Lab 3',
    type: 'Lab',
    semester: 6,
    section: 'CSE-A',
  },
  // Thursday
  {
    id: 'tt-thu-1',
    day: 'Thursday',
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    subjectId: 'sub-kcs603',
    subjectCode: 'KCS-603',
    subjectName: 'Computer Networks',
    facultyName: 'Dr. Neha Saxena',
    roomNumber: 'LH-306',
    type: 'Theory',
    semester: 6,
    section: 'CSE-A',
  },
  {
    id: 'tt-thu-2',
    day: 'Thursday',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    subjectId: 'sub-kcs502',
    subjectCode: 'KCS-502',
    subjectName: 'Compiler Design',
    facultyName: 'Prof. R.K. Dixit',
    roomNumber: 'LH-302',
    type: 'Theory',
    semester: 6,
    section: 'CSE-A',
  },
  {
    id: 'tt-thu-3',
    day: 'Thursday',
    startTime: '11:15 AM',
    endTime: '12:15 PM',
    subjectId: 'sub-knc501',
    subjectCode: 'KNC-501',
    subjectName: 'Constitution of India',
    facultyName: 'Dr. Meena Tripathi',
    roomNumber: 'LH-204',
    type: 'Theory',
    semester: 6,
    section: 'CSE-A',
  },
  {
    id: 'tt-thu-4',
    day: 'Thursday',
    startTime: '01:30 PM',
    endTime: '03:30 PM',
    subjectId: 'sub-kcs652',
    subjectCode: 'KCS-652',
    subjectName: 'Web Technology Lab',
    facultyName: 'Er. Amit Shukla',
    roomNumber: 'Lab 4',
    type: 'Lab',
    semester: 6,
    section: 'CSE-A',
  },
  // Friday
  {
    id: 'tt-fri-1',
    day: 'Friday',
    startTime: '09:00 AM',
    endTime: '10:00 AM',
    subjectId: 'sub-kcs602',
    subjectCode: 'KCS-602',
    subjectName: 'Web Technology',
    facultyName: 'Er. Amit Shukla',
    roomNumber: 'LH-305',
    type: 'Theory',
    semester: 6,
    section: 'CSE-A',
  },
  {
    id: 'tt-fri-2',
    day: 'Friday',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    subjectId: 'sub-kcs503',
    subjectCode: 'KCS-503',
    subjectName: 'Design and Analysis of Algorithms',
    facultyName: 'Dr. Sunita Verma',
    roomNumber: 'LH-303',
    type: 'Theory',
    semester: 6,
    section: 'CSE-A',
  },
  {
    id: 'tt-fri-3',
    day: 'Friday',
    startTime: '11:15 AM',
    endTime: '12:15 PM',
    subjectId: 'sub-kcs601',
    subjectCode: 'KCS-601',
    subjectName: 'Software Engineering',
    facultyName: 'Prof. Manoj Kumar',
    roomNumber: 'LH-304',
    type: 'Theory',
    semester: 6,
    section: 'CSE-A',
  },
  {
    id: 'tt-fri-4',
    day: 'Friday',
    startTime: '01:30 PM',
    endTime: '03:30 PM',
    subjectId: 'sub-kcs653',
    subjectCode: 'KCS-653',
    subjectName: 'Computer Networks Lab',
    facultyName: 'Er. Sandeep Joshi',
    roomNumber: 'Lab 3',
    type: 'Lab',
    semester: 6,
    section: 'CSE-A',
  },
];

// Sessional and internal marks for students across AKTU core subjects
export const INITIAL_MARKS: MarkRecord[] = [
  // Vikas Gupta (student-vikas)
  {
    id: 'mark-vikas-kcs501',
    studentId: 'student-vikas',
    studentName: 'Vikas Gupta',
    rollNumber: '2200270100002',
    subjectId: 'sub-kcs501',
    subjectCode: 'KCS-501',
    subjectName: 'Database Management Systems',
    semester: 6,
    internal1: 28,
    internal2: 29,
    assignmentMarks: 19,
    attendanceMarks: 10,
    totalInternal: 48,
    totalMarks: 94,
    grade: 'A+',
    remarks: 'Outstanding grasp of SQL query optimization and BCNF normalization.',
  },
  {
    id: 'mark-vikas-kcs502',
    studentId: 'student-vikas',
    studentName: 'Vikas Gupta',
    rollNumber: '2200270100002',
    subjectId: 'sub-kcs502',
    subjectCode: 'KCS-502',
    subjectName: 'Compiler Design',
    semester: 6,
    internal1: 27,
    internal2: 28,
    assignmentMarks: 18,
    attendanceMarks: 9,
    totalInternal: 46,
    totalMarks: 91,
    grade: 'A+',
    remarks: 'Flawless LALR(1) parser table computation and TAC generation.',
  },
  {
    id: 'mark-vikas-kcs503',
    studentId: 'student-vikas',
    studentName: 'Vikas Gupta',
    rollNumber: '2200270100002',
    subjectId: 'sub-kcs503',
    subjectCode: 'KCS-503',
    subjectName: 'Design and Analysis of Algorithms',
    semester: 6,
    internal1: 29,
    internal2: 29,
    assignmentMarks: 20,
    attendanceMarks: 10,
    totalInternal: 49,
    totalMarks: 96,
    grade: 'A+',
    remarks: 'Exceptional mathematical derivation of DP states and KMP prefix analysis.',
  },
  {
    id: 'mark-vikas-kcs601',
    studentId: 'student-vikas',
    studentName: 'Vikas Gupta',
    rollNumber: '2200270100002',
    subjectId: 'sub-kcs601',
    subjectCode: 'KCS-601',
    subjectName: 'Software Engineering',
    semester: 6,
    internal1: 26,
    internal2: 27,
    assignmentMarks: 19,
    attendanceMarks: 9,
    totalInternal: 45,
    totalMarks: 88,
    grade: 'A',
    remarks: 'High-quality IEEE-830 SRS documentation and UML architecture design.',
  },
  {
    id: 'mark-vikas-kcs602',
    studentId: 'student-vikas',
    studentName: 'Vikas Gupta',
    rollNumber: '2200270100002',
    subjectId: 'sub-kcs602',
    subjectCode: 'KCS-602',
    subjectName: 'Web Technology',
    semester: 6,
    internal1: 29,
    internal2: 30,
    assignmentMarks: 20,
    attendanceMarks: 10,
    totalInternal: 50,
    totalMarks: 97,
    grade: 'A+',
    remarks: 'Built an industry-standard full-stack React and Express authenticated portal.',
  },
  {
    id: 'mark-vikas-kcs603',
    studentId: 'student-vikas',
    studentName: 'Vikas Gupta',
    rollNumber: '2200270100002',
    subjectId: 'sub-kcs603',
    subjectCode: 'KCS-603',
    subjectName: 'Computer Networks',
    semester: 6,
    internal1: 27,
    internal2: 28,
    assignmentMarks: 18,
    attendanceMarks: 9,
    totalInternal: 46,
    totalMarks: 90,
    grade: 'A',
    remarks: 'Clear understanding of TCP sliding window dynamics and VLSM subnetting.',
  },

  // Ankit Kannaujiya
  {
    id: 'mark-ankit-k-kcs501',
    studentId: 'student-ankit-k',
    studentName: 'Ankit Kannaujiya',
    rollNumber: '2200270100001',
    subjectId: 'sub-kcs501',
    subjectCode: 'KCS-501',
    subjectName: 'Database Management Systems',
    semester: 6,
    internal1: 26,
    internal2: 27,
    assignmentMarks: 18,
    attendanceMarks: 9,
    totalInternal: 44,
    totalMarks: 87,
    grade: 'A',
    remarks: 'Consistently strong analytical performance in ER modeling.',
  },
  {
    id: 'mark-ankit-k-kcs503',
    studentId: 'student-ankit-k',
    studentName: 'Ankit Kannaujiya',
    rollNumber: '2200270100001',
    subjectId: 'sub-kcs503',
    subjectCode: 'KCS-503',
    subjectName: 'Design and Analysis of Algorithms',
    semester: 6,
    internal1: 27,
    internal2: 28,
    assignmentMarks: 19,
    attendanceMarks: 10,
    totalInternal: 47,
    totalMarks: 91,
    grade: 'A+',
    remarks: 'Excellent recursive algorithm formulations.',
  },

  // Krishna Yadav
  {
    id: 'mark-krishna-kcs503',
    studentId: 'student-krishna',
    studentName: 'Krishna Yadav',
    rollNumber: '2200270100003',
    subjectId: 'sub-kcs503',
    subjectCode: 'KCS-503',
    subjectName: 'Design and Analysis of Algorithms',
    semester: 6,
    internal1: 29,
    internal2: 30,
    assignmentMarks: 20,
    attendanceMarks: 10,
    totalInternal: 50,
    totalMarks: 98,
    grade: 'A+',
    remarks: 'Class topper in Graph Algorithms and NP reductions.',
  },

  // Ragini Gangwar
  {
    id: 'mark-ragini-kcs502',
    studentId: 'student-ragini',
    studentName: 'Ragini Gangwar',
    rollNumber: '2200270100006',
    subjectId: 'sub-kcs502',
    subjectCode: 'KCS-502',
    subjectName: 'Compiler Design',
    semester: 6,
    internal1: 30,
    internal2: 30,
    assignmentMarks: 20,
    attendanceMarks: 10,
    totalInternal: 50,
    totalMarks: 99,
    grade: 'A+',
    remarks: 'Exemplary parser construction and lexical analysis benchmarks.',
  },
];

// AKTU Engineering Assignments
export const INITIAL_ASSIGNMENTS: Assignment[] = [
  {
    id: 'asg-kcs501-1',
    title: 'ER to Relational Schema Mapping & BCNF Decomposition',
    subjectId: 'sub-kcs501',
    subjectCode: 'KCS-501',
    subjectName: 'Database Management Systems',
    description: 'Design an EER model for a multi-specialty hospital management system and mathematically prove lossless join decomposition for Boyce-Codd Normal Form (BCNF).',
    dueDate: '2026-09-24',
    maxMarks: 20,
    semester: 6,
    section: 'CSE-A',
    assignedDate: '2026-09-10',
    status: 'Active',
  },
  {
    id: 'asg-kcs502-1',
    title: 'Construction of LALR(1) Parsing Table & Lexical Tokenizer',
    subjectId: 'sub-kcs502',
    subjectCode: 'KCS-502',
    subjectName: 'Compiler Design',
    description: 'Implement a Lex specification for a miniature subset of C and generate canonical LR(1) collection of items followed by table merging for LALR(1).',
    dueDate: '2026-09-28',
    maxMarks: 20,
    semester: 6,
    section: 'CSE-A',
    assignedDate: '2026-09-12',
    status: 'Active',
  },
  {
    id: 'asg-kcs503-1',
    title: 'Dynamic Programming for Matrix Chain Multiplication & 0/1 Knapsack',
    subjectId: 'sub-kcs503',
    subjectCode: 'KCS-503',
    subjectName: 'Design and Analysis of Algorithms',
    description: 'Write optimal substructure proofs and implement memoized vs tabulated algorithms with exact asymptotic time and space comparisons in C++ or Python.',
    dueDate: '2026-10-02',
    maxMarks: 20,
    semester: 6,
    section: 'CSE-A',
    assignedDate: '2026-09-14',
    status: 'Upcoming',
  },
  {
    id: 'asg-kcs602-1',
    title: 'Full-Stack MERN / React Authenticated REST API',
    subjectId: 'sub-kcs602',
    subjectCode: 'KCS-602',
    subjectName: 'Web Technology',
    description: 'Build a secure role-based campus resource booking portal utilizing React hooks on the front end, Express middlewares for JWT validation, and MongoDB indexing.',
    dueDate: '2026-10-08',
    maxMarks: 25,
    semester: 6,
    section: 'CSE-A',
    assignedDate: '2026-09-15',
    status: 'Upcoming',
  },
  {
    id: 'asg-kcs603-1',
    title: 'Variable Length Subnet Masking (VLSM) & Socket Programming',
    subjectId: 'sub-kcs603',
    subjectCode: 'KCS-603',
    subjectName: 'Computer Networks',
    description: 'Solve the campus network IP allocation problem using VLSM CIDR blocks, and implement a concurrent multi-client chat server using raw TCP sockets.',
    dueDate: '2026-10-12',
    maxMarks: 20,
    semester: 6,
    section: 'CSE-A',
    assignedDate: '2026-09-16',
    status: 'Upcoming',
  },
];

// AKTU Examination Schedule
export const INITIAL_EXAMS: Exam[] = [
  {
    id: 'exam-aktu-1',
    title: 'Pre-University Sessional 1: Database Management Systems',
    subjectId: 'sub-kcs501',
    subjectCode: 'KCS-501',
    subjectName: 'Database Management Systems',
    date: '2026-09-29',
    startTime: '10:00 AM',
    endTime: '12:00 PM',
    roomNumber: 'Lecture Hall 301 & 302',
    totalMarks: 50,
    semester: 6,
    syllabus: [
      'Unit 1: ER-to-Relational Mapping, Three-Schema Architecture',
      'Unit 2: Relational Algebra, Calculus, SQL DDL/DML, Triggers, Views',
      'Unit 3: Functional Dependencies, Attribute Closure, 1NF, 2NF, 3NF, BCNF',
    ],
  },
  {
    id: 'exam-aktu-2',
    title: 'Pre-University Sessional 1: Compiler Design',
    subjectId: 'sub-kcs502',
    subjectCode: 'KCS-502',
    subjectName: 'Compiler Design',
    date: '2026-10-01',
    startTime: '10:00 AM',
    endTime: '12:00 PM',
    roomNumber: 'Lecture Hall 303 & 304',
    totalMarks: 50,
    semester: 6,
    syllabus: [
      'Unit 1: Structure of Compiler, Token Recognition, Thompson NFA to DFA',
      'Unit 2: LL(1) Parsing Table Construction, FIRST & FOLLOW Computation, Shift-Reduce Parsing',
    ],
  },
  {
    id: 'exam-aktu-3',
    title: 'Pre-University Sessional 1: Design and Analysis of Algorithms',
    subjectId: 'sub-kcs503',
    subjectCode: 'KCS-503',
    subjectName: 'Design and Analysis of Algorithms',
    date: '2026-10-03',
    startTime: '10:00 AM',
    endTime: '12:00 PM',
    roomNumber: 'Lecture Hall 305 & 306',
    totalMarks: 50,
    semester: 6,
    syllabus: [
      'Unit 1: Asymptotic Notations (O, Ω, Θ), Master Theorem, Quick & Merge Sort analysis',
      'Unit 2: Red-Black Trees, Binomial Heaps, Union-Find Rank heuristic',
      'Unit 3: Greedy Strategy vs DP, 0/1 Knapsack, Longest Common Subsequence',
    ],
  },
  {
    id: 'exam-aktu-4',
    title: 'Pre-University Sessional 1: Computer Networks',
    subjectId: 'sub-kcs603',
    subjectCode: 'KCS-603',
    subjectName: 'Computer Networks',
    date: '2026-10-06',
    startTime: '10:00 AM',
    endTime: '12:00 PM',
    roomNumber: 'Lecture Hall 301 & 302',
    totalMarks: 50,
    semester: 6,
    syllabus: [
      'Unit 1: OSI vs TCP/IP Layers, Physical Transmission Media, Packet Switching',
      'Unit 2: CRC Polynomial Division, Hamming Code, Go-Back-N & Selective Repeat ARQ',
      'Unit 3: IPv4 Addressing, Classless CIDR, Subnet Masks, ARP, ICMP',
    ],
  },
  {
    id: 'exam-aktu-5',
    title: 'Pre-University Sessional 1: Web Technology',
    subjectId: 'sub-kcs602',
    subjectCode: 'KCS-602',
    subjectName: 'Web Technology',
    date: '2026-10-08',
    startTime: '10:00 AM',
    endTime: '12:00 PM',
    roomNumber: 'Lecture Hall 303 & 304',
    totalMarks: 50,
    semester: 6,
    syllabus: [
      'Unit 1: HTTP/2 Request Headers, Semantic HTML5, CSS3 Grid & Flexbox',
      'Unit 2: ES6+ JavaScript, Event Loop, Promises, Async/Await, DOM APIs',
      'Unit 3: Node.js Non-blocking event loop, Express REST API, Route Middlewares',
    ],
  },
  {
    id: 'exam-aktu-6',
    title: 'Practical University Exam: Web Technology & Networks Lab',
    subjectId: 'sub-kcs652',
    subjectCode: 'KCS-652 / KCS-653',
    subjectName: 'Web Technology & Networks Practical',
    date: '2026-10-14',
    startTime: '01:30 PM',
    endTime: '04:30 PM',
    roomNumber: 'Advanced Web & Networks Lab',
    totalMarks: 50,
    semester: 6,
    syllabus: [
      'Experiment coding and viva: Full-Stack React API, Wireshark packet capture, and Socket programming.',
    ],
  },
];

export const INITIAL_NOTIFICATIONS: CampusNotification[] = [
  {
    id: 'notif-aktu-1',
    title: 'AKTU 6th Semester Exam Schedule Announced',
    message: 'Dr. A.P.J. Abdul Kalam Technical University (AKTU) 6th Semester theory examinations commence from late October 2026. Hall tickets will be issued following mandatory 75% attendance verification.',
    category: 'Exam',
    priority: 'high',
    target: 'all',
    createdAt: '2026-09-12T09:00:00Z',
    read: false,
  },
  {
    id: 'notif-aktu-2',
    title: 'Mandatory 75% Biometric Attendance Compliance',
    message: 'All B.Tech 3rd year students (CSE-A & CSE-B) must ensure their biometric face recognition records meet the minimum 75% threshold across KCS-501, KCS-502, KCS-503, and KCS-603.',
    category: 'Attendance',
    priority: 'urgent',
    target: 'students',
    createdAt: '2026-09-11T14:30:00Z',
    read: false,
  },
  {
    id: 'notif-aktu-3',
    title: 'AKTU State Level Hackathon 2026 Registration Open',
    message: 'Entries are open for AKTU Inter-College AI & Cloud Hackathon. Top innovative project teams receive cash rewards and incubation mentorship at Lucknow Campus.',
    category: 'Academic',
    priority: 'medium',
    target: 'all',
    createdAt: '2026-09-10T11:00:00Z',
    read: true,
  },
  {
    id: 'notif-aktu-4',
    title: 'New Biometric Face Kiosk Deployed in CSE Block',
    message: 'High-speed AI face recognition kiosks have been calibrated at the entry of LH-301 and LH-302. Students with registered faces can mark contactless attendance upon entry.',
    category: 'Administrative',
    priority: 'medium',
    target: 'all',
    createdAt: '2026-09-08T10:00:00Z',
    read: true,
  },
];

// Generate past 14 days of realistic attendance records for the 16 students
export function generateInitialAttendance(): AttendanceRecord[] {
  const records: AttendanceRecord[] = [];
  const subjects = INITIAL_SUBJECTS.slice(0, 8); // Core theory subjects
  const daysAgo = 14;
  const now = new Date();

  // Generate records for Vikas Gupta (student-vikas) - ~92% attendance
  for (let i = daysAgo; i >= 1; i--) {
    const targetDate = new Date(now);
    targetDate.setDate(now.getDate() - i);
    const dayOfWeek = targetDate.getDay();

    if (dayOfWeek === 0 || dayOfWeek === 6) continue; // Skip weekends

    const dateStr = targetDate.toISOString().split('T')[0];

    subjects.slice(0, 4).forEach((sub, idx) => {
      const isAbsent = i === 6 && idx === 1; // Only 1 absence
      const isLate = i === 9 && idx === 0;
      const status: 'Present' | 'Absent' | 'Late' = isAbsent ? 'Absent' : isLate ? 'Late' : 'Present';

      records.push({
        id: `att-vikas-${dateStr}-${sub.code}`,
        studentId: 'student-vikas',
        studentName: 'Vikas Gupta',
        rollNumber: '2200270100002',
        subjectId: sub.id,
        subjectCode: sub.code,
        subjectName: sub.name,
        date: dateStr,
        time: idx === 0 ? '09:02 AM' : idx === 1 ? '10:03 AM' : idx === 2 ? '11:17 AM' : '01:32 PM',
        sessionSlot: idx === 0 ? '09:00 - 10:00 AM' : idx === 1 ? '10:00 - 11:00 AM' : idx === 2 ? '11:15 - 12:15 PM' : '01:30 - 02:30 PM',
        status,
        method: isAbsent ? 'manual' : 'face',
        verifiedBy: 'AI Biometric Kiosk #1 (LH-301)',
        timestamp: targetDate.getTime(),
      });
    });
  }

  // Generate records for other students (Ankit Kannaujiya, Krishna Yadav, Ragini Gangwar, etc.)
  INITIAL_STUDENTS.slice(1).forEach((student) => {
    for (let i = 10; i >= 1; i--) {
      const targetDate = new Date(now);
      targetDate.setDate(now.getDate() - i);
      if (targetDate.getDay() === 0 || targetDate.getDay() === 6) continue;
      const dateStr = targetDate.toISOString().split('T')[0];

      subjects.slice(0, 3).forEach((sub, idx) => {
        // Deterministic status based on student roll
        const charCode = student.name.charCodeAt(0) + i + idx;
        const isAbsent = charCode % 7 === 0;
        const isLate = charCode % 13 === 0;
        const status: 'Present' | 'Absent' | 'Late' = isAbsent ? 'Absent' : isLate ? 'Late' : 'Present';

        records.push({
          id: `att-${student.id}-${dateStr}-${sub.code}`,
          studentId: student.id,
          studentName: student.name,
          rollNumber: student.rollNumber,
          subjectId: sub.id,
          subjectCode: sub.code,
          subjectName: sub.name,
          date: dateStr,
          time: idx === 0 ? '09:04 AM' : idx === 1 ? '10:05 AM' : '11:19 AM',
          sessionSlot: idx === 0 ? '09:00 - 10:00 AM' : idx === 1 ? '10:00 - 11:00 AM' : '11:15 - 12:15 PM',
          status,
          method: isAbsent ? 'manual' : 'face',
          verifiedBy: 'AI Biometric Kiosk #2',
          timestamp: targetDate.getTime(),
        });
      });
    }
  });

  return records;
}
